_common: &common
  "test-result-base": "test_results"

"clean.packages":
  <<: *common
"build":
  <<: *common
  "executor": "parallel"
  "parallel-workers": 4
  "symlink-install": true
"test":
  <<: *common
  "executor": "parallel"
  "parallel-workers": 1
  "ctest-args": ["--output-junit", "ctest.junit.xml"]
"test-result":
  <<: *common
